import {
  Target,
  Footprints,
  Gauge,
  Clock,
  Thermometer,
  AlertTriangle,
  Shield,
  Zap,
  Scale,
  Briefcase,
  Droplet,
  Baby,
  User,
  Users,
  Hand,
  Smile,
  Bone,
  PersonStanding,
  Activity,
  TrendingUp,
  Flag,
  CircleCheck,
  Syringe,
  Scissors,
  BookOpen,
  Calendar,
  Stethoscope,
  Gem,
  BookText,
  // Navigation (matches the app's nav icon reference sheet)
  LayoutDashboard,
  Library,
  Layers,
  ScanSearch,
  Dumbbell,
  BookOpenText,
  Camera,
  ClipboardList,
  GraduationCap,
  Sparkles,
  NotebookPen,
  Bookmark,
  History,
  Download,
  FolderKanban,
  // Books / documents
  Book,
  FileText,
  Files,
  Folder,
  FolderOpen,
  Clipboard,
  Notebook,
  type LucideIcon,
} from "lucide-react";

// Small, curated set for ad-hoc card icons (e.g. a risk-factor or
// contributing-factor card) — distinct from objectIcons.tsx, which maps
// Knowledge Object *types* to a fixed icon. These are just decoration
// an author picks per-card, not tied to any object's identity.
export const cardIcons = {
  target: Target,
  footprints: Footprints,
  gauge: Gauge,
  clock: Clock,
  thermometer: Thermometer,
  "alert-triangle": AlertTriangle,
  shield: Shield,
  zap: Zap,
  scale: Scale,
  briefcase: Briefcase,
  droplet: Droplet,
  baby: Baby,
  user: User,
  users: Users,
  hand: Hand,
  smile: Smile,
  bone: Bone,
  "person-standing": PersonStanding,
  activity: Activity,
  "trending-up": TrendingUp,
  flag: Flag,
  "circle-check": CircleCheck,
  syringe: Syringe,
  scissors: Scissors,
  "book-open": BookOpen,
  calendar: Calendar,
  stethoscope: Stethoscope,
  gem: Gem,
  "book-text": BookText,

  // Navigation
  dashboard: LayoutDashboard,
  index: Layers,
  library: Library,
  conditions: Stethoscope,
  procedures: Syringe,
  examination: ScanSearch,
  rehabilitation: Dumbbell,
  "visual-atlas": BookOpenText,
  anatomy: PersonStanding,
  imaging: Camera,
  guidelines: ClipboardList,
  "board-review": GraduationCap,
  "clinical-cases": Briefcase,
  "ai-assistant": Sparkles,
  notes: NotebookPen,
  bookmarks: Bookmark,
  recent: History,
  downloads: Download,
  workspace: FolderKanban,

  // Books / documents
  book: Book,
  "file-text": FileText,
  files: Files,
  folder: Folder,
  "folder-open": FolderOpen,
  clipboard: Clipboard,
  notebook: Notebook,
} satisfies Record<string, LucideIcon>;

export type CardIconName = keyof typeof cardIcons;
