import type { ForwardRefExoticComponent, RefAttributes, SVGProps } from "react";
import {
  // Body regions still without a real anatomy icon (see
  // anatomyIcons.tsx, which now owns Spine/Shoulder/Elbow/Hand &
  // Fingers with real Flaticon-sourced joint icons) — Hip and Knee
  // still fall back to Health Icons' nearest generic stand-in
  // (`Joints` reused from Knee, since Health Icons has no elbow icon
  // anymore needing it either — kept anyway as the honest "generic
  // joint" fallback for Knee specifically).
  Joints,
  Leg,
  Foot,
  // Imaging
  Xray,
  Sonography,
  UltrasoundScanner,
  Radiology,
  Microscope,
  // Physical examination / vitals
  Stethoscope,
  BloodPressure,
  Thermometer,
  PulseOximeter,
  // Procedures
  SyringeVaccine,
  Biopsy,
  Cpr,
  Defibrillator,
  IntravenousDrip,
  IntravenousBag,
  Stitches,
  Staples,
  Cast,
  Sling,
  Bandaged,
  // Rehabilitation
  PhysicalTherapy,
  OccupationalTherapy,
  SpeechLanguageTherapy,
  Exercise,
  ExerciseBicycle,
  ExerciseYoga,
  Walking,
  Running,
  Swim,
  Gym,
  Weights,
  Wheelchair,
  WheelchairAlt,
  Crutches,
  Cane,
  // MSK pathologies / clinical status
  BackPain,
  Headache,
  Fever,
  FeverEmotions,
  Coughing,
  Diarrhea,
  Nausea,
  Diabetes,
  Asthma,
  AutoimmuneDisease,
  Traumatism,
  Pain,
  PainManagment,
  // Specialty categories
  Cardiology,
  Neurology,
  Orthopaedics,
  Rheumatology,
  Gastroenterology,
  Nephrology,
  Urology,
  Endocrinology,
  Geriatrics,
  Pediatrics,
  Gynecology,
  Psychology,
  Oncology,
  Odontology,
  NeuroSurgery,
  GeneralSurgery,
  PediatricSurgery,
  // Devices / equipment
  OxygenTank,
  Ventilator,
  VentilatorAlt,
  HearingAid,
  // Care team / educational & evidence content
  Doctor,
  Nurse,
  HealthWorker,
  Ambulance,
  Telemedicine,
  MedicalAdvice,
  MedicalRecords,
  MedicalSample,
  MedicalSearch,
  ICertificatePaper,
  ChartBar,
} from "healthicons-react/outline";

type MedicalIcon = ForwardRefExoticComponent<Omit<SVGProps<SVGSVGElement>, "ref"> & RefAttributes<SVGSVGElement>>;

// The PM&R Atlas medical icon library — Health Icons (healthicons.org,
// MIT/CC0), sourced rather than hand-drawn (founder call, after
// reviewing hand-drawn pilots: "instead of creating from scratch, cant
// you go and get them from somewhere?"). Filled-glyph style, kept as
// its own visually distinct family from the stroke-based Lucide set in
// cardIcons.ts rather than force-blended with it (founder call, round
// 2: "Health Icons, as its own distinct family").
export const medicalIcons = {
  hip: Leg,
  knee: Joints,
  "foot-ankle": Foot,

  xray: Xray,
  sonography: Sonography,
  "ultrasound-scanner": UltrasoundScanner,
  radiology: Radiology,
  microscope: Microscope,

  stethoscope: Stethoscope,
  "blood-pressure": BloodPressure,
  thermometer: Thermometer,
  "pulse-oximeter": PulseOximeter,

  "syringe-vaccine": SyringeVaccine,
  biopsy: Biopsy,
  cpr: Cpr,
  defibrillator: Defibrillator,
  "iv-drip": IntravenousDrip,
  "iv-bag": IntravenousBag,
  stitches: Stitches,
  staples: Staples,
  cast: Cast,
  sling: Sling,
  bandage: Bandaged,

  "physical-therapy": PhysicalTherapy,
  "occupational-therapy": OccupationalTherapy,
  "speech-therapy": SpeechLanguageTherapy,
  exercise: Exercise,
  "exercise-bicycle": ExerciseBicycle,
  "exercise-yoga": ExerciseYoga,
  walking: Walking,
  running: Running,
  swimming: Swim,
  gym: Gym,
  weights: Weights,
  wheelchair: Wheelchair,
  "wheelchair-alt": WheelchairAlt,
  crutches: Crutches,
  cane: Cane,

  "back-pain": BackPain,
  headache: Headache,
  fever: Fever,
  "fever-emotions": FeverEmotions,
  coughing: Coughing,
  diarrhea: Diarrhea,
  nausea: Nausea,
  diabetes: Diabetes,
  asthma: Asthma,
  "autoimmune-disease": AutoimmuneDisease,
  traumatism: Traumatism,
  pain: Pain,
  "pain-management": PainManagment,

  cardiology: Cardiology,
  neurology: Neurology,
  orthopaedics: Orthopaedics,
  rheumatology: Rheumatology,
  gastroenterology: Gastroenterology,
  nephrology: Nephrology,
  urology: Urology,
  endocrinology: Endocrinology,
  geriatrics: Geriatrics,
  pediatrics: Pediatrics,
  gynecology: Gynecology,
  psychology: Psychology,
  oncology: Oncology,
  odontology: Odontology,
  "neuro-surgery": NeuroSurgery,
  "general-surgery": GeneralSurgery,
  "pediatric-surgery": PediatricSurgery,

  "oxygen-tank": OxygenTank,
  ventilator: Ventilator,
  "ventilator-alt": VentilatorAlt,
  "hearing-aid": HearingAid,

  doctor: Doctor,
  nurse: Nurse,
  "health-worker": HealthWorker,
  ambulance: Ambulance,
  telemedicine: Telemedicine,
  "medical-advice": MedicalAdvice,
  "medical-records": MedicalRecords,
  "medical-sample": MedicalSample,
  "medical-search": MedicalSearch,
  certificate: ICertificatePaper,
  "chart-bar": ChartBar,
} satisfies Record<string, MedicalIcon>;

export type MedicalIconName = keyof typeof medicalIcons;
